include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
    avoid_web_libraries_in_flutter: ignore
    avoid_shadowing_type_parameters: ignore
  exclude:
    - build/**
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart

linter:
  rules:

    # --- ЧИСТЫЙ КОД ---
    - always_declare_return_types
    - avoid_dynamic_calls
    - avoid_empty_else
    - avoid_print
    - avoid_redundant_argument_values
    - avoid_returning_null
    - avoid_returning_null_for_void
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    - avoid_unnecessary_containers
    - avoid_void_async
    - directives_ordering
    - eol_at_end_of_file
    - no_logic_in_create_state
    - prefer_final_fields
    - prefer_final_locals
    - prefer_single_quotes
    - require_trailing_commas
    - sort_child_properties_last
    - unnecessary_await_in_return
    - unnecessary_lambdas
    - unnecessary_parenthesis

    # --- CONST / ОПТИМИЗАЦИЯ РЕНДЕРА ---
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations

    # --- ЧИТАБЕЛЬНОСТЬ / СТИЛЬ ---
    - camel_case_types
    - library_names
    - use_super_parameters
    - use_named_constants
    - prefer_relative_imports
    - unnecessary_const
    - unnecessary_this

    # --- НИЗКОУРОВНЕВАЯ ОПТИМИЗАЦИЯ ---
    - prefer_inlined_adds
    - prefer_is_empty
    - prefer_spread_collections
    - avoid_type_to_string
    - prefer_interpolation_to_compose_strings

    # --- БЕЗОПАСНОСТЬ / NULL-SAFETY ---
    - null_check_on_nullable_type_parameter
    - close_sinks
    - cancel_subscriptions